config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :competitors do
      resources :averages, except: [:new, :create]
    end
    resources :competition_events do
      resources :rounds do
        resources :solves
      end
    end
  end

  root 'competitions#index'

end

app/models/competition_event.rb
class CompetitionEvent < ActiveRecord::Base
  belongs_to :competition
  has_many   :solves
  has_many   :competitors
  has_many   :rounds

  attr_accessor :e_3x3, :e_2x2, :e_skewb
end

app/controllers/competition_events_controller.rb
class CompetitionEventsController < ApplicationController
  before_action :set_competition
  before_action :set_competition_event, only: [:show, :edit, :update, :destroy]
  before_action :set_competition_events, only: [:new]
  before_action :set_competitors, only: [:show]

  # GET /competition_events
  # GET /competition_events.json
  def index
    @competition_events = CompetitionEvent.all
  end

  # GET /competition_events/1
  # GET /competition_events/1.json
  def show
    @allcompetition_eventSolves = []
    @competitors.each do |competitor|
      @solves = []
      for i in 1..5
        if competitor.solves.exists?(:competitor_id => competitor, solve_number: i)
          @solve = competitor.solves.where(:competitor_id => competitor, solve_number: i).take
          @solves.push(@solve)
        end
      end
      @allcompetition_eventSolves.push(@solves)
    end
    @numCompetitors = 0
end

  # GET /competition_events/new
  def new
    @competition_event = @competition.competition_events.new
    @meta_events = ["e_3x3", "e_2x2", "e_skewb"]

    # for each event that already has a record created, remove it from the meta_events array.
    @competition.competition_events.each do |event|
      @event_name_plus_event_tag = "e_" + "#{event.name}"

      @meta_events.delete(@event_name_plus_event_tag)
    end
    @event_count = 0
  end

  # GET /competition_events/1/edit
  def edit
  end

  # POST /competition_events
  # POST /competition_events.json
  def create
    @meta_events = ["e_3x3", "e_2x2", "e_skewb"]
    @errors = []

    @meta_events.each do |event|
      if params["competition_event"][event] == "1"
        @competition_event = @competition.competition_events.new(competition_event_params)
        @competition_event.name = event[2..-1]
        @competition_event.num_competitors = 0

        if @competition_event.save
        else
          @errors.push(@competition_event.errors)
        end
      end
    end

redirect_to competition_path(@competition)





  end

  # PATCH/PUT /competition_events/1
  # PATCH/PUT /competition_events/1.json
  def update
    respond_to do |format|
      if @competition_event.update(competition_event_params)
        format.html { redirect_to competition_competition_event_path(@competition, @competition_event), notice: 'competition_event was successfully updated.' }
        format.json { render :show, status: :ok, location: competition_competition_event_path(@competition, @competition_event) }
      else
        format.html { render :edit }
        format.json { render json: @competition_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competition_events/1
  # DELETE /competition_events/1.json
  def destroy
    @competition_event.destroy
    respond_to do |format|
      format.html { redirect_to competition_competition_events_path(@competition), notice: 'competition_event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition_event
      @competition_event = @competition.competition_events.find(params[:id])
    end

    def set_competition_events
      @competition_events = @competition.competition_events.all
    end

    def set_competition
      @competition = Competition.find(params[:competition_id])
    end

    def set_competitors
      @competitors = Competitor.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_event_params
      params.require(:competition_event).permit(:name, :competition_id, :num_competitors, :e_3x3, :e_2x2, :e_skewb)
    end
end

app/helpers/competition_events_helper.rb
module CompetitionEventsHelper
end

app/views/competition_events/_editForm.html.erb
<%= form_for @competition_event, :url => competition_competition_event_path(@competition_event) do |f| %>
<% if @competition_event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@competition_event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% @competition_event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :competition_id %><br>
  <%= f.number_field :competition_id %>
</div>
<div class="field">
  <%= f.label :num_competitors %><br>
  <%= f.number_field :num_competitors %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/competition_events/_form.html.erb
<%= form_for([@competition, @competition_event], :html => { :class => "form-stacked"}) do |f| %>
  <% if @competition_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition_event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @competition_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

<!-- for each event that does not already have a record, create a checkbox and title -->
<% @meta_events.each do |event| %>

<div class="col-xs-1">
  <div class="field">
    <%= event[2..-1] %> <br>
    <%= f.check_box event %>
  </div>
</div>

<% @event_count = @event_count + 1 %>
<% end %>








<% @meta_events.each do |event| %>

<% end %>
<%= select_tag "events", options_from_collection_for_select(@meta_events, "events", "events") %>
















    <div class="col-xs-<%= "#{12 - @event_count}" %>"></div>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/competition_events/edit.html.erb
<h1>Editing Event</h1>
<%= render 'form' %>

app/views/competition_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<div class="row">

<!-- table header -->
  <div class="row noMargin">
    <div class="col-xs-8">
      <div class="row">
          <div class="col-xs-4">Name</div>
          <div class="col-xs-4">Competition</div>
          <div class="col-xs-4">Num Competitiors</div>
      </div>
    </div>
      <div class="col-xs-4"></div>
    </div>

<!-- create a new row for each competition_event -->
    <% @competition_events.each do |competition_event| %>
    <div class="row noMargin">
      <div class="col-xs-8">
        <div class="row">
            <div class="col-xs-4"><%= link_to competition_event.name, competition_competition_event_path(@competition, competition_event) %></div>
            <div class="col-xs-4"><%= competition_event.competition_id %></div>
            <div class="col-xs-4"><%= competition_event.num_competitors %></div>
        </div>
      </div>
        <div class="col-xs-4">
         <%= link_to 'Edit ', edit_competition_competition_event_path(@competition, competition_event) %><%= link_to 'Destroy', competition_competition_event_path(@competition, competition_event), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>

    <div class="row noMargin">
      <div class="col-xs-8">
        <div class="row">
            <div class="col-xs-4"><%= link_to competition_event.name, competition_competition_event_path(@competition, competition_event) %></div>
            <div class="col-xs-4"><%= competition_event.competition_id %></div>
            <div class="col-xs-4"><%= competition_event.num_competitors %></div>
        </div>
      </div>
        <div class="col-xs-4">
         <%= link_to 'Edit ', edit_competition_competition_event_path(@competition, competition_event) %><%= link_to 'Destroy', competition_competition_event_path(@competition, competition_event), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>


      <br>




  </div>
<%= link_to 'New event', new_competition_competition_event_path(@competition, @competition_event) %>
</div>

app/views/competition_events/new.html.erb
<h1>New Event</h1>
<%= render 'form' %>

app/views/competition_events/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Competitors</h1>

<table class="table">
  <thead>
    <tr>
        <th>Name</th>
        <th>Competition</th>
        <th>Solves</th>
        <th>Buttons</th>
    </tr>
  </thead>

  <tbody>
    <% @competitors.each do |competitor| %>
      <tr>
        <td><%= link_to competitor.name, competition_competition_event_competitor_path(@competition.id, @competition_event, competitor) %></td>
        <td></td>
        <td><% @allcompetition_eventSolves[@numCompetitors].each do |solve| %>
          <%= solve.solve_time %>
        <% end %></td>
        <td><%= link_to 'Destroy', competition_competition_event_competitor_path(@competition.id, @competition_event, competitor), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Edit', edit_competition_competition_event_competitor_path(@competition.id, @competition_event, competitor) %></td>
      </tr>
      <% @numCompetitors = @numCompetitors + 1 %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_competition_competition_event_round_path(@competition, @competition_event) %>