config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :competitors do
      resources :averages, except: [:new, :create]
    end
    resources :competition_events do
      resources :rounds do
        resources :solves
      end
    end
  end

  root 'competitions#index'

end

app/models/competition.rb
class Competition < ActiveRecord::Base
  has_many :competition_events
  has_many :competitors
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  before_action :set_competition_events, only: [:show, :edit]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all

  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    def set_competition_events
      @competition_events = @competition.competition_events.all
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
<% if @competition.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

    <ul>
    <% @competition.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<%= link_to 'Add Event', new_event_path %>

app/views/competitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Competitions</h1>

<%= link_to "Events", competition_competition_events_path(1) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Filler</th>
      <th>Filler</th>
    </tr>
  </thead>

  <tbody class="alternate-row-colors">
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= link_to competition.name, competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<%= link_to "Add Event", new_competition_competition_event_path(@competition) %>

<div class="row">

<!-- table header -->
  <div class="row noMargin">
    <div class="col-xs-8">
      <div class="row">
          <div class="col-xs-4">Name</div>
          <div class="col-xs-4">Competition</div>
          <div class="col-xs-4">Num Competitiors</div>
      </div>
    </div>
      <div class="col-xs-4"></div>
    </div>

<!-- create a new row for each Event -->
    <% @competition_events.each do |event| %>
    <div class="row noMargin">
      <div class="col-xs-8">
        <div class="row">
            <div class="col-xs-4"><%= link_to event.name, competition_competition_event_path(@competition, event) %></div>
            <div class="col-xs-4"><%= event.competition_id %></div>
            <div class="col-xs-4"><%= event.num_competitors %></div>
        </div>
      </div>
        <div class="col-xs-4">
         <%= link_to 'Edit ', edit_competition_competition_event_path(@competition, event) %><%= link_to 'Destroy', competition_competition_event_path(@competition, event), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %><br>
  </div>

</div>