config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :competitors do
      resources :averages, except: [:new, :create]
    end
    resources :competition_events do
      resources :rounds do
        resources :solves
      end
    end
  end

  root 'competitions#index'

end

app/models/solve.rb
class Solve < ActiveRecord::Base
  belongs_to :round
  belongs_to :competition_event
  belongs_to :average

  validates :solve_number, uniqueness: { scope: :competitor_id }
end

app/controllers/solves_controller.rb
class SolvesController < ApplicationController
  before_action :set_competition
  before_action :set_competition_event
  before_action :set_competitor, except: [:index, :new]
  before_action :set_competitors
  before_action :set_round
  before_action :set_solve, only: [:show, :edit, :update, :destroy]

  # GET /solves
  # GET /solves.json
  def index
    @solves = Solve.all
  end

  # GET /solves/1
  # GET /solves/1.json
  def show

  end

  # GET /solves/new
  def new
    byebug
    @solve = @round.solves.build
    render :layout => "new"
  end

  # GET /solves/1/edit
  def edit
  end

  # POST /solves
  # POST /solves.json
  def create
    @solve = Solve.new(solve_params)

    respond_to do |format|
      if @solve.save
        format.html { redirect_to competition_competition_event_path(@competition, @competition_event), notice: 'Solve was successfully created.' }
        format.json { render :show, status: :created, location: @solve }
      else
        format.html { render :new }
        format.json { render json: @solve.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solves/1
  # PATCH/PUT /solves/1.json
  def update
    respond_to do |format|
      if @solve.update(solve_params)
        format.html { redirect_to @solve, notice: 'Solve was successfully updated.' }
        format.json { render :show, status: :ok, location: @solve }
      else
        format.html { render :edit }
        format.json { render json: @solve.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solves/1
  # DELETE /solves/1.json
  def destroy
    @solve.destroy
    respond_to do |format|
      format.html { redirect_to solves_url, notice: 'Solve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solve
      @solve = Solve.find(params[:id])
    end

    def set_competition_event
      @competition_event = @competition_event = CompetitionEvent.find(params[:competition_event_id])
    end

    def set_competitor
      @competitor = Competitor.find(params[:competitor_id])
    end

    def set_competitors
      @competitors = Competitor.all
    end

    def set_round
      @round = Round.find(params[:round_id])
    end

    def set_competition
      @competition = Competition.find(params[:competition_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solve_params
      params.require(:solve).permit(:round_id, :competition_event_id, :solve_time, :solve_number, :status)
    end
end

app/helpers/solves_helper.rb
module SolvesHelper
end

app/views/solves/_form.html.erb
<%= form_for([@competition, @competition_event, @round, @solve], :html => { :class => "form-stacked"}) do |f| %>
  <% if @solve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solve.errors.count, "error") %> prohibited this solve from being saved:</h2>

      <ul>
      <% @solve.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :competitor_id %><br>
    <%= f.text_field :competitor_id %>
  </div>

  <div class="field">
    <%= f.label :round_id %><br>
    <%= f.text_field :round_id %>
  </div>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>

  <div class="field">
    <%= f.label :solve_time %><br>
    <%= f.text_field :solve_time %>
  </div>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, ['Okay', '+2', 'DNF'] %>
  </div>

  <div class="field">
    <%= f.label :solve_number %><br>
    <%= f.number_field :solve_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solves/edit.html.erb
<h1>Editing solve</h1>

<%= render 'form' %>

<%= link_to 'Show', @solve %>

app/views/solves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Solves</h1>

<table>
  <thead>
    <tr>
      <th>Competitor</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solves.each do |solve| %>
      <tr>
        <td><%= solve.competitor_id %></td>
        <td><%= solve.event_id %></td>
        <td><%= link_to 'Show', solve %></td>
        <td><%= link_to 'Edit', edit_competition_event_solve_path(@competition, @competition_event, @solve) %></td>
        <td><%= link_to 'Destroy', solve, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/solves/new.html.erb
<h1>New solve</h1>
<div class="row">
  <div class="col-md-4">
    <div class="well">

    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default container-fluid">
      <div class="row">
        <div class="col-xs-1 no-padding">id</div>
        <div class="col-xs-1 no-padding">Place</div>
        <div class="col-xs-2 no-padding">Name</div>
        <div class="col-xs-1 no-padding">Time 1</div>
        <div class="col-xs-1 no-padding">Time 2</div>
        <div class="col-xs-1 no-padding">Time 3</div>
        <div class="col-xs-1 no-padding">Time 4</div>
        <div class="col-xs-2 no-padding">Time 5</div>
        <div class="col-xs-1 no-padding">Average</div>
        <div class="col-xs-1 no-padding"></div>
      </div>

      <div class="row">
        <div class="col-xs-1 no-padding"></div>
        <div class="col-xs-1 no-padding"></div>
        <div class="col-xs-2 no-padding"></div>
        <div class="col-xs-1 no-padding"></div>
        <div class="col-xs-1 no-padding"></div>
        <div class="col-xs-1 no-padding"></div>
        <div class="col-xs-1 no-padding"></div>
        <div class="col-xs-2 no-padding"></div>
        <div class="col-xs-1 no-padding"></div>
        <div class="col-xs-1 no-padding"></div>
      </div>
    </div>
  </div>
</div>

app/views/solves/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Competitors</h1>

<div class="row">

<!-- table header -->
  <div class="row noMargin">
    <div class="col-xs-8">
      <div class="row">
          <div class="col-xs-4">Name</div>
          <div class="col-xs-4">Time</div>
          <div class="col-xs-4">Status</div>
      </div>
    </div>
      <div class="col-xs-4"></div>
    </div>

<!-- create a new row for each Event -->
    <% @competition_events.each do |event| %>
    <div class="row noMargin">
      <div class="col-xs-8">
        <div class="row">
            <div class="col-xs-4"><%= link_to event.name, competition_event_path(@competition, event) %></div>
            <div class="col-xs-4"><%= event.competition_id %></div>
            <div class="col-xs-4"><%= event.num_competitors %></div>
        </div>
      </div>
        <div class="col-xs-4">
         <%= link_to 'Edit ', edit_competition_event_path(@competition, event) %><%= link_to 'Destroy', competition_event_path(@competition, event), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %><br>
  </div>
<%= link_to 'New Event', new_competition_event_path(@competition, @competition_event) %>
</div>