config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :competitors do
      resources :averages, except: [:new, :create]
    end
    resources :competition_events do
      resources :rounds do
        resources :solves
      end
    end
  end

  root 'competitions#index'

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :competition_event
  has_many :averages
  has_many :solves

  validates :round_number, uniqueness: { scope: :competition_event }
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_competition
  before_action :set_competition_event
  before_action :redirect_to_solves, except: [:new, :create, :show]
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @competitors = Competitor.all
    @allEventSolves = []
    @competitors.each do |competitor|
      @solves = []
      for i in 1..5
        if competitor.solves.exists?(:competitor_id => competitor, solve_number: i)
          @solve = competitor.solves.where(:competitor_id => competitor, solve_number: i).take
          @solves.push(@solve)
        end
      end
      @allEventSolves.push(@solves)
    end
    @numCompetitors = 0
  end

  # GET /rounds/new
  def new
    @round = @competition_event.rounds.build
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = @competition_event.rounds.build(round_params)
    @round.competition_event_id = @competition_event.id

    respond_to do |format|
      if @round.save
        format.html { redirect_to competition_competition_event_round_path(@competition, @competition_event, @round), notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to competition_competition_event_round_path(@competition, @competition_event, @round), notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def redirect_to_solves
      redirect_to competition_competition_event_round_solves_path(@competition, @competition_event, Round.where(round_number: 1, competition_event_id: params[:competition_event_id])[0].id)
    end

    def set_round
      @round = @competition_event.rounds.find(params[:id])
    end

    def set_competition_event
      @competition_event = @competition_event = CompetitionEvent.find(params[:competition_event_id])
    end

    def set_competition
      @competition = Competition.find(params[:competition_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:round_number, :competition_event_id)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_for([@competition, @competition_event, @round], :html => { :class => "form-stacked"}) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round_number %><br>
    <%= f.number_field :round_number %>
  </div>

  <div class="field">
    <%= f.label :competition_event_id %><br>
    <%= f.number_field :competition_event_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rounds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= link_to "#{@competition_event.name} #{round.round_number}", competition_event_round_path(@competition, @competition_event, round) %></td>
        <td><%= link_to 'Edit', edit_competition_event_round_path(@competition, @competition_event, round) %></td>
        <td><%= link_to 'Destroy', competition_event_round_path(@competition, @competition_event, round), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_competition_event_round_path(@competition, @competition_event, @round) %>

app/views/rounds/new.html.erb
<h1>New Round</h1>

<%= render 'form' %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Competitors</h1>

<table class="table">
  <thead>
    <tr>
        <th>Name</th>
        <th>Competition</th>
        <th>Solves</th>
        <th>Buttons</th>
    </tr>
  </thead>

  <tbody>
    <% @competitors.each do |competitor| %>
      <tr>
        <td><%= link_to competitor.name, competition_event_competitor_path(@competition.id, @competition_event, competitor) %></td>
        <td></td>
        <td><% @allEventSolves[@numCompetitors].each do |solve| %>
          <%= solve.solve_time %>
        <% end %></td>
        <td><%= link_to 'Destroy', competition_event_competitor_path(@competition.id, @competition_event, competitor), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Edit', edit_competition_event_competitor_path(@competition.id, @competition_event, competitor) %></td>
      </tr>
      <% @numCompetitors = @numCompetitors + 1 %>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Round', new_competition_competition_event_round_solve_path(@competition, @competition_event, @round) %>

<br>